# Generated by Django 5.2.5 on 2026-04-25 08:29

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('ceo', models.CharField(blank=True, max_length=200)),
                ('manager', models.CharField(blank=True, max_length=200)),
                ('email', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True, validators=[app1.models.validate_phone_length])),
                ('social_links', models.TextField(blank=True)),
                ('front_image', models.ImageField(upload_to='cards/')),
                ('back_image', models.ImageField(upload_to='cards/')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
