# Generated by Django 5.0.14 on 2026-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='social_links',
            field=models.TextField(blank=True),
        ),
    ]
