# Generated by Django 5.2.7 on 2026-04-18 03:43

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contact_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(blank=True, validators=[app1.models.validate_phone_length]),
        ),
    ]
